# Generated by Django 5.2.8 on 2025-11-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код города')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GarsRawEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255, verbose_name='Тип сущности (коллекция OData)')),
                ('ref_key', models.CharField(db_index=True, max_length=255, verbose_name='Ключ записи (Ref_Key)')),
                ('payload', models.JSONField(verbose_name='Полный JSON записи OData')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сырая запись ГАРС',
                'verbose_name_plural': 'Сырые записи ГАРС',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=100, verbose_name='ID маршрута')),
                ('passenger_name', models.CharField(max_length=255, verbose_name='Пассажир')),
                ('status', models.CharField(default='created', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.CharField(max_length=255, verbose_name='Данные QR')),
                ('status', models.CharField(default='active', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
